model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 4096 # TODO: 1. decrease max txt length
  image_size: 448
  end_sym: "</s>"
  llama_model: "models/Meta-Llama-3-8B-Instruct"
  ckpt: "models/minigptv2_checkpoint.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64 # TODO: 1. tune lora params
  lora_alpha: 16

datasets:

  cc_sbu_align:
    batch_size: 2 #3
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448 # TODO: 1. test with low res, 2. test with high res
    text_processor:
       train:
        name: "blip_caption"
    sample_ratio: 10  # TODO: 1. sample ratio

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5 # TODO: check lrs
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 50
  num_workers: 6
  warmup_steps: 1000
  iters_per_epoch: 1000

  seed: 42
  output_dir: "/work/pi_donghyunkim_umass_edu/hochul/emnlp/kthk/MiniGPT-4/output"

  amp: True
  resume_ckpt_path: null
  # resume_ckpt_path: "/work/pi_donghyunkim_umass_edu/hochul/emnlp/kthk/MiniGPT-4/output/20240503221/checkpoint_25.pth"

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigptv2_finetune


  # EXPERIMENT PLAN
  #     1. COCO checkpoint use/not
  #     2. LoRA params
  #     3. lr
